#!/bin/sh
#---------------------------------------------------------------------------#
# Copyright (C) 2001 The University of Melbourne.
# This file may only be copied under the terms of the GNU General
# Public License - see the file COPYING in the Mercury distribution.
#---------------------------------------------------------------------------#
#
# Usage: gdbrun <program> <arguments>
# Invokes gdb on <program>, and runs the program with the given <arguments>.
#
program="$1"
tmpfile=/tmp/gdbrun.$$
trap "rm -f $tmpfile" 0 1 2 3 13 15
shift
echo -n "run " > "$tmpfile"
for arg in "$@"
do
	if echo "$arg" | grep " " > /dev/null
	then
		echo -n "\"$arg\" " >> $tmpfile
	else
		echo -n "$arg " >> $tmpfile
	fi
done
echo >> $tmpfile

echo gdb --command="$tmpfile" $program
gdb --command="$tmpfile" $program
